// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noqfvtvbnvpasrlaqcon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcWZ2dHZibnZwYXNybGFxY29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzAyMTksImV4cCI6MjA2Mjc0NjIxOX0.Z21n4wdbdNq1Qdxqo7fvd2BKQVb6viorGqbHZPQ79pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);